
package Queues;


enum PriorityThingyHaoTeaches {
    HIGH, MEDIUM, LOW;
    //ENUMS IMPLEMENT COMPARABLE
    //FIRST IS SMALLEST, PRIORITY QUEUE GIVES YOU IT FIRST
    //CHANGE INT TO "PRIORITY"
        //CHANGE CONDITION == TO HIGH, MEDIUM, LOW (IN PATIENT PROGRAM)
}
